name: Deploy pages

on: 
 push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build application
        run: |
          yarn build
          cp dist/index.html dist/404.html
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: dist
        env:
          GITHUB_TOKEN: ${{ secrets.KIRBY_PRES_TOKEN }}
